// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Domain;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(MovieManagementContext))]
    [Migration("20230904071544_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("api.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Should contain numerous scenes where action is spectacular and usually destructive. Often includes non-stop motion, high energy physical stunts, chases, battles, and destructive crises (floods, explosions, natural disasters, fires, etc.) Note: if a movie contains just one action scene (even if prolonged, i.e. airplane-accident) it does not qualify. Subjective.",
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Should contain numerous consecutive and inter-related scenes of characters participating in hazardous or exciting experiences for a specific goal. Often include searches or expeditions for lost continents and exotic locales, characters embarking in treasure hunt or heroic journeys, travels, and quests for the unknown. Not to be confused with Action, and should only sometimes be supplied with it.",
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Virtually all scenes should contain characters participating in humorous or comedic experiences. The comedy can be exclusively for the viewer, at the expense of the characters in the title, or be shared with them. Please submit qualifying keywords to better describe the humor (i.e. spoof, parody, irony, slapstick, satire, dark-comedy, comedic-scene, etc.). If the title does not conform to the 'virtually all scenes' guideline then please do not add the comedy genre; instead, submit the same keyword variations described above to signify the comedic elements of the title. The subgenre keyword \"dramedy-drama\" can also be used to categorize titles with comedic undertones that qualify for the Drama genre but not necessarily the Comedy genre.",
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Whether the protagonists or antagonists are criminals this should contain numerous consecutive and inter-related scenes of characters participating, aiding, abetting, and/or planning criminal behavior or experiences usually for an illicit goal. Not to be confused with Film-Noir, and only sometimes should be supplied with it.",
                            Name = "Crime"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Should contain numerous consecutive scenes of characters portrayed to effect a serious narrative throughout the title, usually involving conflicts and emotions. This can be exaggerated upon to produce melodrama.",
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Should contain numerous consecutive scenes of characters portrayed to effect a magical and/or mystical narrative throughout the title. Usually has elements of magic, supernatural events, mythology, folklore, or exotic fantasy worlds.Note: not to be confused with Sci-Fi which is not usually based in magic or mysticism.",
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Should contain numerous consecutive scenes of characters effecting a terrifying and/or repugnant narrative throughout the title. Note: not to be confused with Thriller which is not usually based in fear or abhorrence.",
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Should contain numerous sensational scenes or a narrative that is sensational or suspenseful. Note: not to be confused with Mystery or Horror, and should only sometimes be accompanied by one (or both).",
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Should contain numerous scenes and/or a narrative where the portrayal is similar to that of frontier life in the American West during 1600s to contemporary times.",
                            Name = "Western"
                        });
                });

            modelBuilder.Entity("api.Domain.Entities.Director", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Directors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1951, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "John McTiernan was born on January 8, 1951 in Albany, New York, USA. He is a director and producer, known for Die Hard (1988), Rollerball (2002) and Last Action Hero (1993). He has been married to Gail Sistrunk since 2012. He was previously married to Kate Harrington, Donna Dubrow and Carol Land.",
                            FirstName = "John",
                            LastName = "McTiernan"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1961, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sir Peter Jackson made history with The Lord of the Rings trilogy, becoming the first person to direct three major feature films simultaneously. The Fellowship of the Ring, The Two Towers and The Return of the King were nominated for and collected a slew of awards from around the globe, with The Return of the King receiving his most impressive collection of awards.",
                            FirstName = "Peter",
                            LastName = "Jackson"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1906, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Originally planning to become a lawyer, Billy Wilder abandoned that career in favor of working as a reporter for a Viennese newspaper, using this experience to move to Berlin, where he worked for the city's largest tabloid. He broke into films as a screenwriter in 1929 and wrote scripts for many German films until Adolf Hitler came to power in 1933.",
                            FirstName = "Billy",
                            LastName = "Wilder"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(1963, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Quentin Jerome Tarantino was born in Knoxville, Tennessee. His father, Tony Tarantino, is an Italian-American actor and musician from New York, and his mother, Connie (McHugh), is a nurse from Tennessee. Quentin moved with his mother to Torrance, California, when he was four years old.In January of 1992, first-time writer-director Tarantino's Reservoir Dogs (1992) appeared at the Sundance Film Festival.",
                            FirstName = "Quentin",
                            LastName = "Tarantino"
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(1951, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Three-time Oscar nominee Frank Darabont was born in a refugee camp in 1959 in Montbeliard, France, the son of Hungarian parents who had fled Budapest during the failed 1956 Hungarian revolution. Brought to America as an infant, he settled with his family in Los Angeles and attended Hollywood High School.",
                            FirstName = "Frank",
                            LastName = "Darabont"
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateTime(1958, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Born in Pennsylvania and raised in Ohio, Chris Columbus was first inspired to make movies after seeing \"The Godfather\" at age 15. After enrolling at NYU film school, he sold his first screenplay (never produced) while a sophomore there. After graduation Columbus tried to sell his fourth script, \"Gremlins\", with no success, until Steven Spielberg optioned it; Columbus moved to Los Angeles for a year during rewrites on the project in Spielberg's bungalow at Universal.",
                            FirstName = "Chris",
                            LastName = "Columbus"
                        },
                        new
                        {
                            Id = 7,
                            DateOfBirth = new DateTime(1928, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Stanley Kubrick was born in Manhattan, New York City, to Sadie Gertrude (Perveler) and Jacob Leonard Kubrick, a physician. His family were Jewish immigrants (from Austria, Romania, and Russia). Stanley was considered intelligent, despite poor grades at school. Hoping that a change of scenery would produce better academic performance, Kubrick's father sent him in 1940 to Pasadena, California, to stay with his uncle, Martin Perveler.",
                            FirstName = "Stanley",
                            LastName = "Kubrick"
                        },
                        new
                        {
                            Id = 8,
                            DateOfBirth = new DateTime(1961, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Darren Aronofsky was born February 12, 1969, in Brooklyn, New York. Growing up, Darren was always artistic: he loved classic movies and, as a teenager, he even spent time doing graffiti art. After high school, Darren went to Harvard University to study film (both live-action and animation). He won several film awards after completing his senior thesis film, \"Supermarket Sweep\", starring Sean Gullette, which went on to becoming a National Student Academy Award finalist. Aronofsky didn't make a feature film until five years later, in February 1996, where he began creating the concept for Pi (1998).",
                            FirstName = "Darren",
                            LastName = "Aronofsky"
                        },
                        new
                        {
                            Id = 9,
                            DateOfBirth = new DateTime(1921, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sergio Leone was virtually born into the cinema - he was the son of Roberto Roberti (A.K.A. Vincenzo Leone), one of Italy's cinema pioneers, and actress Bice Valerian. Leone entered films in his late teens, working as an assistant director to both Italian directors and U.S. directors working in Italy (usually making Biblical and Roman epics, much in vogue at the time).",
                            FirstName = "Sergio",
                            LastName = "Leone"
                        });
                });

            modelBuilder.Entity("api.Domain.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DirectorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavourite")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOnWatchlist")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.Property<bool>("Watched")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DirectorId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "A New York City police officer tries to save his estranged wife and several others taken hostage by terrorists during a Christmas party at the Nakatomi Plaza in Los Angeles.",
                            DirectorId = 1,
                            Duration = 132,
                            IsFavourite = false,
                            IsOnWatchlist = false,
                            Name = "Die Hard",
                            Rating = 8.1999999999999993,
                            Watched = false
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
                            DirectorId = 2,
                            Duration = 178,
                            IsFavourite = false,
                            IsOnWatchlist = false,
                            Name = "The Lord of the Rings: The Fellowship of the Ring",
                            Rating = 8.8000000000000007,
                            Watched = false
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "After two male musicians witness a mob hit, they flee the state in an all-female band disguised as women, but further complications set in.",
                            DirectorId = 3,
                            Duration = 121,
                            IsFavourite = false,
                            IsOnWatchlist = false,
                            Name = "Some Like It Hot",
                            Rating = 8.1999999999999993,
                            Watched = false
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Description = "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
                            DirectorId = 4,
                            Duration = 154,
                            IsFavourite = true,
                            IsOnWatchlist = false,
                            Name = "Pulp Fiction",
                            Rating = 8.9000000000000004,
                            Watched = true
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            Description = "Over the course of several years, two convicts form a friendship, seeking consolation and, eventually, redemption through basic compassion.",
                            DirectorId = 5,
                            Duration = 144,
                            IsFavourite = true,
                            IsOnWatchlist = false,
                            Name = "The Shawshank Redemption",
                            Rating = 9.3000000000000007,
                            Watched = true
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 6,
                            Description = "An orphaned boy enrolls in a school of wizardry, where he learns the truth about himself, his family and the terrible evil that haunts the magical world.",
                            DirectorId = 6,
                            Duration = 152,
                            IsFavourite = false,
                            IsOnWatchlist = false,
                            Name = "Harry Potter and the Sorcerer's Stone",
                            Rating = 7.5999999999999996,
                            Watched = true
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 7,
                            Description = "A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence, while his psychic son sees horrific forebodings from both past and future.",
                            DirectorId = 7,
                            Duration = 146,
                            IsFavourite = false,
                            IsOnWatchlist = true,
                            Name = "The Shining",
                            Rating = 8.4000000000000004,
                            Watched = false
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 8,
                            Description = "Nina is a talented but unstable ballerina on the verge of stardom. Pushed to the breaking point by her artistic director and a seductive rival, Nina's grip on reality slips, plunging her into a waking nightmare.",
                            DirectorId = 8,
                            Duration = 108,
                            IsFavourite = false,
                            IsOnWatchlist = false,
                            Name = "Black Swan",
                            Rating = 8.0,
                            Watched = false
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 9,
                            Description = "A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.",
                            DirectorId = 9,
                            Duration = 178,
                            IsFavourite = false,
                            IsOnWatchlist = false,
                            Name = "The Good, the Bad and the Ugly",
                            Rating = 8.8000000000000007,
                            Watched = false
                        });
                });

            modelBuilder.Entity("api.Domain.Entities.Movie", b =>
                {
                    b.HasOne("api.Domain.Entities.Category", "Category")
                        .WithMany("Movies")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Domain.Entities.Director", "Director")
                        .WithMany("Movies")
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Director");
                });

            modelBuilder.Entity("api.Domain.Entities.Category", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("api.Domain.Entities.Director", b =>
                {
                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
